### ISSUE TITLE
你的书的链接去哪儿

### ISSUE THREAD

**Issue by wangfeng3769** [lining808/CS-Ebook#2]
看了你的非常喜欢，今天没事准备看看，突然发现没有了。能恢复吗？

**Comment by wangfeng3769** [comment]
你的书太及时了，麻烦分享一下

**Comment by jhualee** [comment]
书籍的链接在哪里啊

**Comment by lining808** [comment]
k可以通过https://zh.zlibrary-east.se/搜索下载

**Comment by lining808** [comment]
可以通过https://zh.zlibrary-east.se  搜索下载
